### ISSUE TITLE
Crash mit bestimmten Werten in jsonrpc.cors.allowed_hosts

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/services-inoeg#24]
Wenn ich `jsonrpc.cors.allowed_hosts` auf `["*"]` setze, wie es `allowed_headers` erlaubt und übliche Konvention wäre, crashed der Server mit folgendem Stacktrace:

```
backend_1  | panic: error parsing regexp: missing argument to repetition operator: `*`
backend_1  |
backend_1  | goroutine 1 [running]:
backend_1  | github.com/kiebitz-oss/services/jsonrpc.Cors(0xc00001f450, 0xc00011f500, 0xffffffffffffffff)
backend_1  | 	/go/src/app/jsonrpc/cors.go:56 +0x216
backend_1  | github.com/kiebitz-oss/services/jsonrpc.MakeJSONRPCServer(0xc00033f970, 0xc00011ad68, 0xbbb4c5, 0xc, 0xc00014ec00, 0xc, 0xc00014ec00, 0x0)
backend_1  | 	/go/src/app/jsonrpc/server.go:92 +0x97
backend_1  | github.com/kiebitz-oss/services/servers.MakeServer(0xbbb4c5, 0xc, 0xc000343530, 0xc00033f970, 0xc00033f840, 0xc000021700, 0xc00011f580, 0xb76300, 0x69bbcc, 0xc000126058)
backend_1  | 	/go/src/app/servers/server.go:60 +0x2a8
backend_1  | github.com/kiebitz-oss/services/servers.MakeAppointments(0xc000328a10, 0x4000000005, 0xc00031e9e0, 0x1)
backend_1  | 	/go/src/app/servers/appointments.go:366 +0x2073
backend_1  | github.com/kiebitz-oss/services/helpers.InitializeAppointmentsServer(...)
backend_1  | 	/go/src/app/helpers/appointments.go:27
backend_1  | github.com/kiebitz-oss/services/cmd/helpers.initializeAppointments(0xc000328a10, 0xc000136dc0, 0xc00022e470, 0x10, 0xc000136dc0)
backend_1  | 	/go/src/app/cmd/helpers/run.go:73 +0x8b
backend_1  | github.com/kiebitz-oss/services/cmd/helpers.startServer(0xc000328a10, 0xbe1f38, 0x1, 0x1)
backend_1  | 	/go/src/app/cmd/helpers/run.go:89 +0x34
backend_1  | github.com/kiebitz-oss/services/cmd/helpers.run.func1(0xc0002ac840, 0xbb7d64, 0x7)
backend_1  | 	/go/src/app/cmd/helpers/run.go:111 +0xaf
backend_1  | github.com/kiebitz-oss/services/cmd/helpers.CLI.func1.1(0xc0002ac840, 0xc000344b00, 0xc000344b30)
backend_1  | 	/go/src/app/cmd/helpers/cli.go:63 +0x13d
backend_1  | github.com/urfave/cli.HandleAction(0xac71e0, 0xc0003448f0, 0xc0002ac840, 0xc0002ac840, 0x0)
backend_1  | 	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
backend_1  | github.com/urfave/cli.Command.Run(0xbb474e, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbc3043, 0x18, 0x0, ...)
backend_1  | 	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
backend_1  | github.com/urfave/cli.(*App).RunAsSubcommand(0xc0002d2380, 0xc0002ac580, 0x0, 0x0)
backend_1  | 	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x914
backend_1  | github.com/urfave/cli.Command.startApp(0xbb484a, 0x3, 0x0, 0x0, 0xc000344860, 0x1, 0x1, 0xbc43a4, 0x1a, 0x0, ...)
backend_1  | 	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x7ff
backend_1  | github.com/urfave/cli.Command.Run(0xbb484a, 0x3, 0x0, 0x0, 0xc000344860, 0x1, 0x1, 0xbc43a4, 0x1a, 0x0, ...)
backend_1  | 	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x9d4
backend_1  | github.com/urfave/cli.(*App).Run(0xc0002d21c0, 0xc00012c000, 0x5, 0x5, 0x0, 0x0)
backend_1  | 	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
backend_1  | github.com/kiebitz-oss/services/cmd/helpers.CLI(0xc000328a10)
backend_1  | 	/go/src/app/cmd/helpers/cli.go:96 +0x3fb
backend_1  | main.main()
backend_1  | 	/go/src/app/cmd/kiebitz/main.go:55 +0x1c8
```

Generell müsste die Validierung das abfangen, wenn nicht erlaubt. Schön wäre aber für's development, wenn man `*` setzen könnte.

**Comment by tauli** [comment]
TIL die Einträge in der `jsonrpc.cors.allowed_hosts` sind regexe die gegen den `Origin` header laufen und wenn einer passt den `Access-Control-Allow-Origin` auf den wert von `Origin` setzen. Müssten wir mal mit Betrieb absprechen, was da sinnvoll ist.

**Comment by adewes** [comment]
Ihr könnt einen Validator dafür hinzufügen z.B. so

```
import (
  "regexp"
)

type IsValidRegexp struct {}

func (i IsValidRegexp) Validate(value interface{}, values map[string]interface{}) (interface{}, error) {
  // Assumes that stringiness has been validated before...
  if _, err := regexp.Compile(value.(string)); err != nil {
    return nil, err
  }
  return value, nil
}
```
Die Yaml-Settings sind nicht alle perfekt validiert da es vertrauenswürdige Daten sind und Fehler beim Startup auffallen. Allowed Hosts werden nicht einfach als Liste zurückgegeben weil das ein Sicherheitsrisiko sein kann, es wird daher immer nur der Origin zurückgegeben falls er einem der regulären Ausdrücke entspricht.

**Comment by tauli** [comment]
@adewes danke für den Tipp, hab's so übernommen.
